#!/usr/bin/python

import curses
import os
import signal
import sys

import debug
import init
import mainloop
import musicdb
            
from loadconf import config

def cleanup(stdscr, exit_f=False):
    if os.path.exists(config.SOCKET):
        os.remove(config.SOCKET)
    
    curses.echo()
    curses.nocbreak()
    stdscr.keypad(0)

    curses.endwin()

    if exit_f:
        sys.exit()


def main():
    if os.path.exists(config.SOCKET):
        sys.exit('sqlmp socket already open')
    
    stdscr = init.ncurses()

    try:
        db = musicdb.Musicdb(config.DBPATH, config.LIBPATH)
    except Exception as e:
        debug.print_error('db error:', e)

    try:
        signal.signal(signal.SIGINT, lambda a, b: cleanup(stdscr, True))
        ui = init.windows(db, stdscr)
        mainloop.mainloop(ui)
        cleanup(stdscr)
    except Exception as e:
        cleanup(stdscr)
        debug.print_error('error:', e)


if __name__ == "__main__":
    main()
